title: Explain your deep fault and improve yourself!
description: Workshop on Explainable Artificial Intelligence approaches for debugging and diagnosis deep neural networks.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman